name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["jobjunction"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What's the bug?
      description: What and where is actually the issue is?
      placeholder: ex. Input form is not getting submitted
    validations:
      required: true
  - type: textarea
    id: how-to-solve
    attributes:
      label: How will you solve it?
      description: If you have any solutions then tell the process?
      placeholder: ex. I will try to remove the form tag..
    validations:
      required: true
  - type: dropdown
    id: interested
    attributes:
      label: Are you willing to solve it
      multiple: false
      options:
        - Yes
        - No
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
