name: Formatting & Linting
run-name: Checking formatting & Linting

on:
  pull_request:
    branches: [main]

jobs:
  Linting-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Copying the source code
        uses: actions/checkout@v4

      - name: Installing dependencies
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm install

      - name: Fixing the formatting
        run: npm run format:fix

      - name: Checking the formatting
        run: npm run format:check

      - name: Linting
        run: npm run lint

      - name: Building
        run: npm run build
